ld:
  host: 127.0.0.1
  mysql-port: 3306
  nacos-port: 8848
  redis-port: 6379
  #rocketmq-port:

#NACOS
nacos:
  #dev
  namespace: 916b89d9-5124-4e5f-b0d5-36af29d8573c


#database
DB_HOST: ${ld.host}:${ld.mysql-port}
DB_NAME: ld
DB_USERNAME: root
DB_PASSWORD: 123456